/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Cryptography.Cryption;
import DB.DB;
import Model.SuggestionList;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import validation.Validation;

/**
 *
 * @author OLE
 */
public class Change_Email extends javax.swing.JPanel {

    /**
     * Creates new form ChangeUserName
     */
    public Change_Email() {
        initComponents();
        nic.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                userName();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                userName();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                userName();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nicDropdown = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        nic = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        c_email = new javax.swing.JTextField();
        n_email = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        username1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 422));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Change Email ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Password");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        password.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("NIC");

        nic.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        nic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nicFocusLost(evt);
            }
        });
        nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicActionPerformed(evt);
            }
        });
        nic.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                nicPropertyChange(evt);
            }
        });
        nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Current Email");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("New Email");

        c_email.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        c_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                c_emailFocusLost(evt);
            }
        });
        c_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c_emailKeyReleased(evt);
            }
        });

        n_email.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        n_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                n_emailFocusLost(evt);
            }
        });
        n_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                n_emailKeyReleased(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        username.setText("User");

        username1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        username1.setText("Username ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)
                                .addGap(120, 120, 120)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nicDropdown, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nic, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4)
                            .addGap(79, 79, 79)
                            .addComponent(n_email, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_email, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(username1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(0, 0, 0)
                .addComponent(nicDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(c_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(n_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicKeyReleased

        SuggestionList.showList(nic, nicDropdown, "SELECT nic FROM employee WHERE status = 1 AND nic LIKE '" + nic.getText() + "%' AND nic <> 0", "nic", evt, this.getClass().getName());
    }

    private void nicDropdownItemStateChanged(java.awt.event.ItemEvent evt) {
        SuggestionList.setSelectedItem(nic, nicDropdown);
        // TODO add your handling code here:
    }//GEN-LAST:event_nicKeyReleased

    private void nicFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nicFocusLost
        // TODO add your handling code here:
        if (!(nic.getText().isEmpty())) {
            if (!(Validation.validateNic(nic.getText()))) {
                JOptionPane.showMessageDialog(this, "NIC you entered is not a valid NIC", "Invalid data", JOptionPane.ERROR_MESSAGE);
                nic.grabFocus();
                nic.setText(null);

            }
        }

    }//GEN-LAST:event_nicFocusLost
    public void userName() {
        try {
            ResultSet rs = DB.search("SELECT username FROM user WHERE employee_nic ='" + nic.getText() + "'");
            if (rs.next()) {
                username.setText(Cryption.decript(rs.getString("username")));
            } else {
                username.setText("INVALID USER");
            }
        } catch (Exception e) {
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean value = true;
        String NIC = nic.getText();
        String PasswordToAccept = this.password.getText();
        String OldEmail = c_email.getText();
        String NewEmail = n_email.getText();
        if (NIC.isEmpty()) {
            JOptionPane.showMessageDialog(this, "NIC cannot be empty", "Empty data", JOptionPane.ERROR_MESSAGE);
            value = false;
        }

        if (!(Validation.validateNic(nic.getText()))) {

            JOptionPane.showMessageDialog(this, "Incorrect NIC", "Error", JOptionPane.ERROR_MESSAGE);
            value = false;
            nic.grabFocus();

        }
        if (OldEmail.isEmpty() || NewEmail.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email Cannot be Empty", "Empty Data", JOptionPane.ERROR_MESSAGE);
            value = false;
        }
            if (!(Validation.validateEmail(c_email.getText()))) {
                JOptionPane.showMessageDialog(this, "Current email is not valid ", "Invalid data", JOptionPane.ERROR_MESSAGE);
                c_email.grabFocus();
                value = false;

            }
            if (!(Validation.validateEmail(n_email.getText()))) {
                JOptionPane.showMessageDialog(this, "New email is not valid ", "Invalid data", JOptionPane.ERROR_MESSAGE);
                n_email.grabFocus();

            }
        if (value) {

            try {
                ResultSet rs = DB.search("SELECT password FROM user WHERE employee_nic = '" + NIC + "'");
                if (rs.next()) {
                    if (rs.getString("password").equals(Cryption.encript(PasswordToAccept))) {
                        rs = DB.search("SELECT email FROM employee WHERE email = '" + OldEmail + "'");

                        if (rs.next()) {
                            DB.iud("UPDATE employee SET email = '" + NewEmail + "' WHERE nic = '" + NIC + "' ");
                            JOptionPane.showMessageDialog(this, "Email updated successfully", "successful", JOptionPane.INFORMATION_MESSAGE);
                            reset();
                        } else {
                            JOptionPane.showMessageDialog(this, "The old email you entered does not match", "Data miss match", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Password is incorrect", "Incorrect password", JOptionPane.ERROR_MESSAGE);
                        password.setText(null);
                        password.grabFocus();

                    }
                } else {
                    JOptionPane.showMessageDialog(this, "You are not a registerd user", "Non user", JOptionPane.ERROR_MESSAGE);
                    nic.grabFocus();
                }
            } catch (Exception e) {
            }

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void c_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c_emailFocusLost
        // TODO add your handling code here:
       

    }//GEN-LAST:event_c_emailFocusLost

    private void c_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_emailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_c_emailKeyReleased

    private void n_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_n_emailFocusLost
        // TODO add your handling code here:
        if (!(n_email.getText().isEmpty())) {
            if (!(Validation.validateEmail(n_email.getText()))) {
                JOptionPane.showMessageDialog(this, "New email is not valid ", "Invalid data", JOptionPane.ERROR_MESSAGE);
                n_email.grabFocus();

            }
        }
    }//GEN-LAST:event_n_emailFocusLost

    private void n_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_n_emailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_n_emailKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nicPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_nicPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_nicPropertyChange

    private void nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_nicActionPerformed
    public void reset() {
        nic.setText(null);
        password.setText(null);
        c_email.setText(null);
        n_email.setText(null);
        username.setText("User");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c_email;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField n_email;
    private javax.swing.JTextField nic;
    private javax.swing.JComboBox<String> nicDropdown;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username1;
    // End of variables declaration//GEN-END:variables
}
